spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/equipment_db
    username: hmood
    password: hmood123

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true