spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/equipment_db}
    username: ${DB_USERNAME:hmood}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true