CREATE TABLE assets
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_user_id BIGINT,
    name            VARCHAR(100) NOT NULL,
    category        VARCHAR(100) NOT NULL,
    serial_number   VARCHAR(100) NOT NULL,
    status          VARCHAR(30)  NOT NULL DEFAULT 'AVAILABLE',
    purchase_date   DATE,

    CONSTRAINT uk_assets_serial_number
        UNIQUE (serial_number),

    CONSTRAINT chk_assets_status
        CHECK (
            status IN (
                       'AVAILABLE',
                       'ASSIGNED',
                       'UNDER_MAINTENANCE',
                       'DAMAGED'
                )
            ),

    CONSTRAINT fk_assets_current_user
        FOREIGN KEY (current_user_id)
            REFERENCES users (id)
);

CREATE INDEX idx_assets_status
    ON assets (status);

CREATE INDEX idx_assets_category
    ON assets (category);