Create TABLE assignments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id    BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL,
    returned_at TIMESTAMPTZ,

    CONSTRAINT fk_assignments_asset
        FOREIGN KEY (asset_id)
            REFERENCES assets (id),

    CONSTRAINT fk_assignments_user
        FOREIGN KEY (user_id)
            REFERENCES users (id),

    CONSTRAINT chk_assignments_returned_at
        CHECK (
            returned_at IS NULL
                OR returned_at >= assigned_at
            )
);

CREATE UNIQUE INDEX uk_assignments_active_asset
    ON assignments (asset_id)
    WHERE returned_at IS NULL;

CREATE INDEX idx_assignments_asset_id
    ON assignments (asset_id);

CREATE INDEX idx_assignments_user_id
    ON assignments (user_id);
